### ISSUE TITLE
Installation&general question

### ISSUE THREAD

**Issue by Chapa1** [joselado/dmrgpy#1]
Hello,
Could you please answer my question:
Is it true that 'dmrgpy' can carry out any calculation that Itensor can do? So, can one use it in research problems?

Could you also help to install  the 'dmrgpy'? 
I use Windows10 and installed Itensor via Cygwin64. 
In Anaconda Prompt I typed `git clone https://github.com/joselado/dmrgpy `
What should I do next?

Thank you.

**Comment by Chapa1** [comment]
After git clone I wrote in Anaconda Prompt `set DMRGROOT="C:/Users/(...)/dmrgpy/src", ` and got the error `ImportError: cannot import name 'spinchain' from 'dmrgpy' (unknown location)`

**Comment by doomspec** [comment]
Me too. 
ImportError: cannot import name 'spinchain'
Though it seems like dmrgpy can be imported.

**Comment by Chapa1** [comment]
How one can install dmrgpy then?

**Comment by joselado** [comment]
Thanks for your message. Unfortunately I think that in the current form the library does not work in Windows. The easiest way to use it would be to install a virtual machine with Linux on it. The library uses some of the functionalities of ITensor, and in its current form can be used to study quasi 1D fermionic and spin systems.

**Comment by Chapa1** [comment]
Thank you for your quick reply. 
As I mentioned "I use Windows10 and installed Itensor via Cygwin64." i.e.  I make use of "a virtual machine with Linux on it". The  DMRGPY is not still working.

**Comment by joselado** [comment]
Hi Chapa1. 

Unfortunately I have no experience with Cygwin64, but I think that it would be easier to run if install a full virtual machine, for instance with Virtual Box, and in Virtual Box you install a (for example) Ubuntu image. In this way, the code should work.
