### ISSUE TITLE
Installtion issue

### ISSUE THREAD

**Issue by 000sadaf** [joselado/dmrgpy#10]
Hi, my name sadaf i am new to python and coding. 
I am using jupyter notebook. 
How I install DMRGpy using pip? 
I am also using window10. 
Thanks

**Comment by joselado** [comment]
Dear 000sadaf,

thank you for your message. Unfortunately, the code does not work in Windows. You can see in the README the instructions to install the code in Linux (unfortunately, so far the code cannot be installed via pip). In your case, you could install a Virtual Machine with Linux in your computer and perform the calculations there.

Best regards,
Jose

**Comment by 000sadaf** [comment]
Hello sir,
I had successfully install the DMRGpy in my laptop but I am facing several
problems. I ran the code for ground state energy for 1d Heisenberg
hamiltonian.
But I am facing some errors 'import error: numba needs numpy 1.20 Or less'.
I already have installed  numpy 1.20.
And there is no documentation for DMRGpy nad no tutorial for this module.
How to solve this problem?
Also I have a request can you please tell me that how to make a code for
spin Correlation for 1d Heisenberg spin Hamiltonian without using dmrg
module.


I had made the code for eigen value and eigen function for 1d Heisenberg
hamiltonian using numpy and sympy.
But facing a problem for spin correlation function.
Thank you so much
Best regards
Sadaf
