### ISSUE TITLE
 import errors

### ISSUE THREAD

**Issue by 000sadaf** [joselado/dmrgpy#11]
hello,
after installation of dmrgpy , i ran one of the given codes ( ground state energy of 1d heisenberg hamiltonian ) in examples .
but there is always some import error regrding numpy and different libraries.
i also ran some other given codes but still got the 'import errors'.
why it is not working.

Thanks
best
sadaf

**Comment by 000sadaf** [comment]
Hi, 
There is no instructions for install the library through anaconda. 
Do I follow the same command which written for linux terminal in anaconda prompt.? 

Best
Sadaf

**Comment by joselado** [comment]
Dear Sadaf,

yes, the code is installed in the same way with Python Anaconda.

Best regards,
Jose
