### ISSUE TITLE
Spectrum with ED

### ISSUE THREAD

**Issue by Vald20** [joselado/dmrgpy#12]
Hello Joselado!!
Can I get the full spectrum of a given Hamiltonian using "Dmrgpy" with ED mode?

**Comment by joselado** [comment]
Hi Vald20,

thank you for your message. With ED you can certainly compute the whole spectra for small system sizes. You just have to write
sc.get_excited(n=None,mode="ED")
where "sc" is your many-body object (a spin chain for example)

Best regards,
Jose
