### ISSUE TITLE
Magnetization of an arbitrary 1D chain

### ISSUE THREAD

**Issue by HamidArianZad** [joselado/dmrgpy#14]
Dear Jose,

I am an ALPS package user. Recently, I have decided to work with DMRG to simulate 1D branched chains, two-leg and three-leg ladders. I found your dmrgpy package that seems to be nice to use in my future projects.
I have a question regarding an arbitrary lattice chain.
ALPS package allows one to construct any lattice for 1D models (lattice.xml) whose sites may have more than one  adjacent spins that are interacted with. 
Does dmrgny have this option? Or it just supports 1D linear chains.
For example, I would like to compute the total magnetization and local magnetization per site for a branched chain as shown in below

![Threeside_Chain](https://user-images.githubusercontent.com/97589591/172728566-27b75586-d15a-472a-9c92-38cac999e270.png)

or for a 3-leg ladder shown in below graph

![ThreeLegLadder](https://user-images.githubusercontent.com/97589591/172728195-4e9f2fb4-3292-46ef-abb6-9185a91d6514.png)

Can I employ dmrgpy package to do these simulations?
If so, please let me know how can I introduce my own 1D lattice to dmrgpy?

As far as I understood, dmrgpy is more efficient rather than ALPS, since it covers more subjects of many-body problem (dynamical properties of 1D models) and is faster to calculate the problems.
Am I right?

**Comment by joselado** [comment]
Dear HamidArianZad,

thank you for your message. You can certainly solve that problem with dmrgpy. When setting up the Hamiltonian, you can include non-local couplings between any sites, realizing the models you mentioned above. You can check how the Hamiltonians are set up in some of the examples, and you would only need to include the specific couplings that would realize the models you want to study.

Regarding the comparison with ALPS, I would say that the two codes have different different strengths. So, depending on the task that you would like carry out, either ALPS or dmrgpy may be more convenient.

Best regards,
Jose
