### ISSUE TITLE
Specify half-filling fermionchain.Spinful_Fermionic_Chain

### ISSUE THREAD

**Issue by HamidArianZad** [joselado/dmrgpy#20]
Hi Jose!

I realized that how it is possible to tune the total number of spinless particles in your sample code:
https://github.com/joselado/dmrgpy/blob/master/examples/total_particle_number/main.py

Is the procedure of finding the total number of spinless electrons described in above code applicable for the case: fermionchain.Spinful_Fermionic_Chain, when I want to have the Hubbard model in half-filling such that there is an imbalance term|N_up - N_dn| = 2? that means <gs|Sz_total|gs> = 1. 

In your code at sufficiently low values of the chemical potential (mu < -3.5) the total number of spinless fermions reaches its highest value ne = 4 that means in half filling case we have ne = 2. For the case spinful fermionic chain I found that the total number of electrons `for i in range(L): Nop = Nop + fc.N[i]` gives one-quarter number of total particles. However, it needs to take into account the sum of total number of particles with spin up (N_up) and those with spins down (N_dn)  all together to get the total number of particles N_total in half-filling. Is that right?

**Comment by joselado** [comment]
Hi HamidArianZad,

yes, you could control the number of particles with a chemical potential also in the case of spinful fermions. 

For a spinful system, one needs to consider both spin and spin down when counting the number of electrons. You can address each of them separately with fc.Nup and fc.Ndn, and the total with Nup + Ndn.

Best regards,
Jose
