### ISSUE TITLE
Sample Example to Calculate the various Quantum Entanglement Measures at Zero T, Finite Temperature

### ISSUE THREAD

**Issue by hcut** [joselado/dmrgpy#24]
Hi Joselado,

I appreciate your library.  It  helps us in learning  and understanding the spin systems.

I have a request for you.

I want to do some calculations on  Quantum Entanglement Measures (Temperature dependent also) such as Concurrence. 
It would be be nice to see some sample example for 1D spin chain, It will great if you can add, suggest some piece of code for doing such calculations.

Thanks.

**Comment by joselado** [comment]
Hi hcut,

thanks for the message. Currently the code does not have implemented calculation of concurrence at finite temperature. This would be of course something that may be included in the future.

Best regards,
Jose
