### ISSUE TITLE
Document / Literature for tutorials in  "examples/entanglement_entropy" folder

### ISSUE THREAD

**Issue by hcut** [joselado/dmrgpy#27]
Hello,
Jose Lado,

Can you suggest some literature/document for the entanglement_entropy tutorials in the folder `examples/entanglement_entropy` ?

Thanks and Regards
hcut

**Comment by joselado** [comment]
Dear hcut,

thank you for your message. The two links below are very nice references about entanglement entropy and matrix product states
https://www.sciencedirect.com/science/article/pii/S0003491610001752?via%3Dihub
https://journals.aps.org/rmp/abstract/10.1103/RevModPhys.90.035007

Best regards,
Jose
