### ISSUE TITLE
Translate an operator to a state.

### ISSUE THREAD

**Issue by apdfjapfjap** [joselado/dmrgpy#28]
Hello Joselado,

I really appreciate you creating this helpful package. I want to know how to transform an operator with a total site of L into a state with a total site of 2L in your code. For example in fermionic system, i need to translate \hat c=c_{i,j}|i><j| to \psi=c_{i,j}|i>|j>. (This requirement is because i want to use your code to solve the lindblad equation. )

Thanks for your time.

**Comment by joselado** [comment]
Dear apdfjapfjap,

thanks for the kind feedback!

In principle one cannot change the size of the system once the system has been created. One possibility of doing what you want is to create form the beginning an auxiliary replica of your system, and write the object that you want as an MPS in this real system + replica. An alternative, perhaps more convenient if you need to deal with some complex case, is that you implement it directly with ITensor.

Best regards,
Jose
