### ISSUE TITLE
Conjugate an MPS or MPO

### ISSUE THREAD

**Issue by apdfjapfjap** [joselado/dmrgpy#29]
Hello Joselado,

I want to know how to conjugate an MPS or MPO, such as for fc.C [i] takes conjugation. But I couldn't find a similar operation in your code example, could you please advise on how to implement this operation.

Thanks for your time.

**Comment by joselado** [comment]
Dear apdfjapfjap,

thanks for the message.

For an MPS "wf1", you can conjugate it by using the bound method

wf2 = wf1.get_conjugate()

This was included today following your comment, so you would need to get the latest version

For an MPO "A", you can compute the Hermitian conjugate as 

B = A.get_dagger()

You can find an example in
https://github.com/joselado/dmrgpy/blob/master/examples/algebra/conjugate/main.py

The conjugate of an MPO is currently not implemented, yet if this is something that you would need let me know and I'll include it in a future update.

Best regards,
Jose

**Comment by apdfjapfjap** [comment]
Dear Jose,

Thank you very much for your patient response and updates！




I have some confusion about the example you provided about MPS. We have wf0.dot(wf0)=\sum_i wf0(i)*Conjute(wf0(i))=1. However, wf1=wf0i.conjugate=conjugate(1j*wf0).

As a result, wf0.dot(wf1)=\sum_i -1j*Conjute(wf0(i))*Conjute(wf0(i)).And this result seem to be -1j only if wf0(i) is real for every i. I do need the conjugation (or transposition) 

of a MPO to implement the Lindblad equation evolution based on your existing code. Therefore, i sincerely hope that you can introduce this in future updates.




May i ask another question about lindblad equation? I try to map a density matrix to a state in a system with twice the length, and map the lindblad operator to a Non-hermitian Hamiltonian. 

Then, i can get expected value of an operator in time t by a Non-hermitian evolving, which can be realized by your “imaginary exponential” function. Can you provide some comments

on the feasibility of this proposal. 




As a beginner, I have browsed through many software packages related to DMRG, but your package is the most comprehensive and user-friendly. Therefore, thank you again for your development！








Best wish,

Shi chen











-----原始邮件-----
发件人:"Jose Lado" ***@***.***>
发送时间:2024-11-13 16:54:11 (星期三)
收件人: joselado/dmrgpy ***@***.***>
抄送: apdfjapfjap ***@***.***>, Author ***@***.***>
主题: Re: [joselado/dmrgpy] Conjugate an MPS or MPO (Issue #29)






Dear apdfjapfjap,

thanks for the message.

For an MPS "wf1", you can conjugate it by using the bound method

wf2 = wf1.get_conjugate()

This was included today following your comment, so you would need to get the latest version

For an MPO "A", you can compute the Hermitian conjugate as

B = A.get_dagger()

You can find an example in
https://github.com/joselado/dmrgpy/blob/master/examples/algebra/conjugate/main.py

The conjugate of an MPO is currently not implemented, yet if this is something that you would need let me know and I'll include it in a future update.

Best regards,
Jose
