### ISSUE TITLE
Repeated calculation of gs when evaluating vev

### ISSUE THREAD

**Issue by doomspec** [joselado/dmrgpy#3]
Hi Jose. Thanks for your awesome package! It helped me very much. 
I am trying to get the vacuum expectation value (vev) of many operators on the ground state. However, I found that the DMRG (or ED) calculations are carried out again and again if I use sc.vev(). I am wondering whether there is a way to reuse the calculated wavefunction?

**Comment by joselado** [comment]
Hi doomspec,

thank you for your nice feedback, it is great to hear that the package has been useful! Regarding your question, I have now made small modification, and now the code will reuse the calculated ground state in DMRG, so vev() will now not rerun the ground state calculation.

Thanks a lot for pointing that out!

Best regards,
Jose
