### ISSUE TITLE
Poor dmrg for large N spin chains

### ISSUE THREAD

**Issue by magnon00** [joselado/dmrgpy#9]
Hi Jose, 
Recently I used your library for finding the GS magnetization of a spin chain using dmrg implementation '(mode="DMRG")'.
I get a smooth curve for small sizes (lets say up to 16), but for higher spin let's 50 or 100, I get a noisy, not so smooth curve. Can you help me in this ?  

Also where we can specify the sweeps and  max-dimension for truncation in your spin chain program for magnetization. I see only mode=DMRG is defined in that.

Thanks.

**Comment by joselado** [comment]
Dear magnon00,

thank you for your message. Probably the reason for the behavior you see is that the default bond dimension and number of sweeps that you are considering is not large enough for your system. To increase the bond dimension, you can just modify the bond dimension in the attribute "maxm" of the Spin_Chain object as

sc.maxm = 300

and for the bond dimension you can modify

sc.nsweeps = 60

where "sc" is the Spin_Chain object.

In particular, in the example in the dmrgpy repository (https://github.com/joselado/dmrgpy) page you can see how to check the converge with respect tot he bond dimension (see image below)

![image](https://user-images.githubusercontent.com/10385143/139533764-a8673a11-4b2d-4a72-ae2d-52094b46c8f1.png)

Best regards,
Jose

**Comment by magnon00** [comment]
Dear Jose,

Thanks for prompt reply and clarification.
